
title: Bench to Brain
description: Exploring regeneration, one neuron at a time
author: Krithika Rajesh
email: krithirajesh@gmail.com
baseurl: ""           # repo root
url: "https://krithikarajesh.github.io"
theme: minima
